<a href="https://colab.research.google.com/github/niteshydv01/Python-AI-Assaignment/blob/main/KNN_Salary_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a dataset (.csv file) having following features- experience of the candidate,
written score, interview score and salary. Based on three input features, HR decide
the salary of the selected candidates. Using this data, KNN model build a for HR
department that can help them decide salaries of the candidates. Predict the salaries
for the following candidates, by executing the model (for different values of K):
(a) 5 Yrs experience, 8 written test score, 10 interview score
(b) 8 Yrs experience, 7 written test score, 6 interview score


In [ ]:
import pandas as pd
import numpy as np

num_entries = 1000

experience = np.random.randint(0, 20, size=num_entries)
written_score = np.random.randint(0, 100, size=num_entries)
interview_score = np.random.randint(0, 100, size=num_entries)

def calculate_salary(experience, written_score, interview_score):
    base_salary = 30000  # Base salary
    salary = base_salary + (experience * 1000) + (written_score * 300) + (interview_score * 500)
    return salary


salary = calculate_salary(experience, written_score, interview_score)


df = pd.DataFrame({
    'Experience': experience,
    'Written Score': written_score,
    'Interview Score': interview_score,
    'Salary': salary
})


df.to_csv('candidate_dataset.csv', index=False)


print(df.head())


   Experience  Written Score  Interview Score  Salary
0          13             11               37   64800
1           2             64               60   81200
2          16             56                8   66800
3           8             85               64   95500
4          17             18               48   76400


In [ ]:
from google.colab import files

files.download('candidate_dataset.csv')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df.shape

(1000, 4)

In [ ]:
import numpy as np

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

def knn_predict(X_train, y_train, X_test, k=5):
    predictions = []
    for i in range(len(X_test)):
        distances = np.array([euclidean_distance(X_test[i], x) for x in X_train])
        nearest_neighbors = np.argsort(distances)[:k]
        k_nearest_labels = [y_train[idx] for idx in nearest_neighbors]
        most_common = max(set(k_nearest_labels), key=k_nearest_labels.count)
        predictions.append(most_common)
    return predictions



In [ ]:
 output=df['Salary']

 df.drop('Salary', axis=1, inplace=True)

In [ ]:
print(output)

0      64800
1      81200
2      66800
3      95500
4      76400
       ...  
995    66100
996    82400
997    88000
998    80900
999    48000
Name: Salary, Length: 1000, dtype: int64


In [ ]:
df.head()

Experience  Written Score  Interview Score
0          13             11               37
1           2             64               60
2          16             56                8
3           8             85               64
4          17             18               48

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Split data into training and test sets
train_data, test_data, train_output,test_output = train_test_split(df, output, test_size=0.2, random_state=42)


In [ ]:
train_data.shape

(800, 3)

In [ ]:
train_data.head()

Experience  Written Score  Interview Score
29            2             75               39
535          14             26               97
695           9             95                3
557          19             11               95
836          10             41               68

In [ ]:
train_data=train_data.values

In [ ]:
print(train_data)

[[ 2 75 39]
 [14 26 97]
 [ 9 95  3]
 ...
 [12 13 63]
 [ 2 73 95]
 [12 81 47]]


In [ ]:
test_data=test_data.values
train_output=train_output.values
test_output=test_output.values


In [ ]:
test_pred=knn_predict(train_data,train_output,train_output)

In [ ]:
print(test_pred)

[119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300, 119300,

In [ ]:
print(test_output)

[ 84900  77000  67600  45500  82900  60500  49900  69400  70000  62000
  92000  78900  75000  95500  59600  69900  95600  87100  53600  35900
  70500  74400  57100  72800  96000 109900 115400 106900  62200  40300
  58800  93200  60700  89500  52600 100400  73400 107800  95800  75900
 101000  76400  87700  84300  64600  75800  93100  73300  78500  96700
  46100  99400  87400 103400 102200  81400  85600  67300  83500  91000
  73200  42100  47800  86600 115600  65900  59500  75600 100900  81200
  66300  66100  55300  73800  79700  92200  97900  79400  81700  54600
  87800  71600  89200  96100  95700  69100  80900 118100  95300  92300
  59300  71600  80000  52600  45900  67300  75900  75800  54300  95800
  80500  75100  63400  95200  86400  98400  66500  58500  69600  68400
  79000  87200 101700  55900  66200  56300  92500  79500  83800  96200
  88000  63600  72400  86200  88500  50000  68400  88500  51100  67000
  57700  71300  81300  66100  95200  83700  69500  70100  61500  59100
  8910